### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by eldarshit** [gered/AppleWirelessKeyboard#2]
This looks like exactly what I was looking for for my wired Apple keyboard.
Call me stupid but if I use uxsofts .exe and run it, how is your folder involved? I don't get it.

**Comment by gered** [comment]
This replaces the uxsoft one. Use this _instead of_ the other one.

**Comment by mattvv** [comment]
@eldarshit I'm assuming you have already figured this out, but the steps are as follows:

1. Clone the Repo
2. Open AppleWirelessKeyboard.sln in Visual Studio
3. Right click on Project Properties, Go to Signing, Disable Signing for project (Or add your own Signature if you like).
4. Build the Project
5. Copy bin/Debug/ApppleWirelessKeyboard.exe to your Start Menu startup folder or wherever you like to use it.

**Comment by vidirh** [comment]
Where can I find the AppleWirelessKeyboard.exe?

**Comment by fredlorry** [comment]
@vidirh 
Here's the [link](https://yadi.sk/d/IGep2BGw3GG8Co) to the built exe that I use.

**Comment by gered** [comment]
There is now a downloadable .exe in the releases page of this repository too.

https://github.com/gered/AppleWirelessKeyboard/releases
