### ISSUE TITLE
Upload a built release

### ISSUE THREAD

**Issue by danjohnson95** [gered/AppleWirelessKeyboard#3]
It would be cool if you created a GitHub release, and uploaded the .exe file to the release.

This would avoid the need to clone the repository and build from source

**Comment by gered** [comment]
I will add one, yes. My apologies!

(There actually used to be a download linked here some years ago. This repository was first created shortly before Github removed their downloads support which is where I originally had the exe posted.)

**Comment by samirotiv** [comment]
Hey, could you please add it? Will be a big help :)

**Comment by gered** [comment]
Sorry, I will add it tonight. I'd forgotten about this completely.

**Comment by gered** [comment]
Here you go! https://github.com/gered/AppleWirelessKeyboard/releases
